diplomado/gemsapp/config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  devise_for :users

  root 'contacts#index'

end

diplomado/gemsapp/app/models/contact.rb
class Contact < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
end

diplomado/gemsapp/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

diplomado/gemsapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

diplomado/gemsapp/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # Desproteger controlador de la autenticacion.
  # skip_before_action :authenticate_user!

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    respond_to do |format|
      format.html {}
      format.pdf do
        archivo_pdf = ContactsPdf.new(@contact, current_user)
        send_data archivo_pdf.render, filename: "#{@contact.name}.pdf", content_type: "application/pdf" and return
      end
    end
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone, :email, :avatar)
    end
end

diplomado/gemsapp/app/helpers/application_helper.rb
module ApplicationHelper
end

diplomado/gemsapp/app/helpers/contacts_helper.rb
module ContactsHelper
end

diplomado/gemsapp/app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

diplomado/gemsapp/app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

diplomado/gemsapp/app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Avatar</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= image_tag contact.avatar, :class => "img_idx" %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Pdf', contact_path(contact, format: "pdf") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path, class: "btn btn-default" %>

diplomado/gemsapp/app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

diplomado/gemsapp/app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Avatar:</strong>
  <%=image_tag @contact.avatar, class: "img" %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Pdf', contact_path(@contact, format: "pdf") %> |
<%= link_to 'Back', contacts_path %>

diplomado/gemsapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gemsapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="pull-right">
    <nav>
      <ul class="nav navbar-default">

  <% if user_signed_in? %>
            <li>
      Logged in as <strong><%= current_user.email %></strong>
            </li>
            <li>
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
            </li>
            <li>
      <%= link_to 'Log out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
            </li>
  <% else %>
      <%= link_to 'Create account', new_user_registration_path, :class => 'nabvar-link' %> |
      <%= link_to 'Sign In', new_user_session_path, :class => 'navbar-link' %>
  <% end %>
      </ul>
    </nav>
  </div>

  <div class="container-fluid">
  <%= yield %>
  </div>
</div>
</body>
</html>