diplomado/diploapp/config/routes.rb
Rails.application.routes.draw do
  resources :computadors
  get 'persona/index'

  get 'persona/saludar'

end

diplomado/diploapp/app/models/computador.rb
class Computador < ActiveRecord::Base
end

diplomado/diploapp/app/models/persona.rb
class Persona < ActiveRecord::Base
  def hola
    "retornando"
  end
end

diplomado/diploapp/app/controllers/computadors_controller.rb
class ComputadorsController < ApplicationController
  before_action :set_computador, only: [:show, :edit, :update, :destroy]

  # GET /computadors
  # GET /computadors.json
  def index
    @computadors = Computador.all
  end

  # GET /computadors/1
  # GET /computadors/1.json
  def show
  end

  # GET /computadors/new
  def new
    @computador = Computador.new
  end

  # GET /computadors/1/edit
  def edit
  end

  # POST /computadors
  # POST /computadors.json
  def create
    @computador = Computador.new(computador_params)

    respond_to do |format|
      if @computador.save
        format.html { redirect_to @computador, notice: 'Computador was successfully created.' }
        format.json { render :show, status: :created, location: @computador }
      else
        format.html { render :new }
        format.json { render json: @computador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /computadors/1
  # PATCH/PUT /computadors/1.json
  def update
    respond_to do |format|
      if @computador.update(computador_params)
        format.html { redirect_to @computador, notice: 'Computador was successfully updated.' }
        format.json { render :show, status: :ok, location: @computador }
      else
        format.html { render :edit }
        format.json { render json: @computador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computadors/1
  # DELETE /computadors/1.json
  def destroy
    @computador.destroy
    respond_to do |format|
      format.html { redirect_to computadors_url, notice: 'Computador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_computador
      @computador = Computador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def computador_params
      params.require(:computador).permit(:procesador, :cant_mem, :cant_disco, :uni_disco, :sisope, :tarj_video, :feac_fab)
    end
end

diplomado/diploapp/app/controllers/persona_controller.rb
class PersonaController < ApplicationController
  def index
    @personas = Persona.all
    @fecha = Time.now.strftime('%m-%d-%Y')
    @hora = Time.now.strftime('%X')
    #Para definir la vista se usa render
    render "persona/index"
  end

  def saludar
    @persona = Persona.count
    @saludo = "desde otro vista"
  end
end

diplomado/diploapp/app/helpers/computadors_helper.rb
module ComputadorsHelper
end

diplomado/diploapp/app/helpers/persona_helper.rb
module PersonaHelper
end

diplomado/diploapp/app/views/computadors/_form.html.erb
<%= form_for(@computador) do |f| %>
  <% if @computador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@computador.errors.count, "error") %> prohibited this computador from being saved:</h2>

      <ul>
      <% @computador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :procesador %><br>
    <%= f.text_field :procesador %>
  </div>
  <div class="field">
    <%= f.label :cant_mem %><br>
    <%= f.number_field :cant_mem %>
  </div>
  <div class="field">
    <%= f.label :cant_disco %><br>
    <%= f.number_field :cant_disco %>
  </div>
  <div class="field">
    <%= f.label :uni_disco %><br>
    <%= f.text_field :uni_disco %>
  </div>
  <div class="field">
    <%= f.label :sisope %><br>
    <%= f.text_field :sisope %>
  </div>
  <div class="field">
    <%= f.label :tarj_video %><br>
    <%= f.text_field :tarj_video %>
  </div>
  <div class="field">
    <%= f.label :feac_fab %><br>
    <%= f.date_select :feac_fab %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

diplomado/diploapp/app/views/computadors/edit.html.erb
<h1>Editing Computador</h1>

<%= render 'form' %>

<%= link_to 'Show', @computador %> |
<%= link_to 'Back', computadors_path %>

diplomado/diploapp/app/views/computadors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Computadors</h1>

<table>
  <thead>
    <tr>
      <th>Procesador</th>
      <th>Cant mem</th>
      <th>Cant disco</th>
      <th>Uni disco</th>
      <th>Sisope</th>
      <th>Tarj video</th>
      <th>Feac fab</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @computadors.each do |computador| %>
      <tr>
        <td><%= computador.procesador %></td>
        <td><%= computador.cant_mem %></td>
        <td><%= computador.cant_disco %></td>
        <td><%= computador.uni_disco %></td>
        <td><%= computador.sisope %></td>
        <td><%= computador.tarj_video %></td>
        <td><%= computador.feac_fab %></td>
        <td><%= link_to 'Show', computador %></td>
        <td><%= link_to 'Edit', edit_computador_path(computador) %></td>
        <td><%= link_to 'Destroy', computador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Computador', new_computador_path %>

diplomado/diploapp/app/views/computadors/new.html.erb
<h1>New Computador</h1>

<%= render 'form' %>

<%= link_to 'Back', computadors_path %>

diplomado/diploapp/app/views/computadors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Procesador:</strong>
  <%= @computador.procesador %>
</p>

<p>
  <strong>Cant mem:</strong>
  <%= @computador.cant_mem %>
</p>

<p>
  <strong>Cant disco:</strong>
  <%= @computador.cant_disco %>
</p>

<p>
  <strong>Uni disco:</strong>
  <%= @computador.uni_disco %>
</p>

<p>
  <strong>Sisope:</strong>
  <%= @computador.sisope %>
</p>

<p>
  <strong>Tarj video:</strong>
  <%= @computador.tarj_video %>
</p>

<p>
  <strong>Feac fab:</strong>
  <%= @computador.feac_fab %>
</p>

<%= link_to 'Edit', edit_computador_path(@computador) %> |
<%= link_to 'Back', computadors_path %>

diplomado/diploapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diploapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

diplomado/diploapp/app/views/persona/index.html.erb
<h1>Persona#index</h1>
<span>Fecha: <%=@fecha %>, Hora: <%=@hora %></span>
<p>Find me in app/views/persona/index.html.erb</p>
<% if @personas.blank? %>
    <h1>No existen registros.</h1>
<% else %>
    <h1>Tengo <%=@personas.count %></h1>
    <!--<h1>Esta <%=@personas[0].hola %></h1>-->
    <div class="caja">
      <table>
      <thead>
      <tr>
        <th>Nombre</th>
        <th>Edad</th>
        <th>Telefono</th>
      </tr>
      </thead>
      <tbody>
        <% @personas.each do |persona| %>
          <tr>
            <td><%=persona.nombre %></td>
            <td><%=persona.edad %></td>
            <td><%=persona.telefono %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
<% end %>

diplomado/diploapp/app/views/persona/saludar.html.erb
<%=@saludo %>
<h1>Esta <%=@persona.hola %></h1>